services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DMF\EnhancedBackend\Service\BackendUserService:
    public: true

  DMF\EnhancedBackend\Service\FeatureService:
    public: true

  DMF\EnhancedBackend\Factory\FeatureFactory:
    public: true

