services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DMF\EnhancedBackend\Service\BackendUserService:
    public: true

  DMF\EnhancedBackend\Service\BackendStyles:
    public: true

  DMF\EnhancedBackend\Service\FeatureService:
    public: true

  TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider: '@DMF\EnhancedBackend\Hooks\EnhancedSvgIconProvider'
  TYPO3\CMS\Core\Imaging\IconProvider\SvgSpriteIconProvider: '@DMF\EnhancedBackend\Hooks\EnhancedSvgSpriteIconProvider'
